<?php
$users->loginAction();
?>
<div class="py-5">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="card text-white p-5 bg-primary">
                    <div class="card-body">
                        <img src="http://localhost/dtt/public/img/dtt.png">
                        <h1 class="mb-4">Admin login</h1>
                        <form method="POST">
                            <div class="form-group">
                                <label>Username</label>
                                <input type="username"  name="username" class="form-control" placeholder="Username"> </div>
                            <div class="form-group">
                                <label>Password</label>
                                <input type="password" name="password" class="form-control" placeholder="Password"> </div>
                            <button type="submit" name="submit" class="btn btn-secondary btn-lg btn-block">Login</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>